### PR TITLE
Re-adding texts module

### PR DESCRIPTION
**Pull request by nathangibson**
The whole texts module/collection needs to be re-added -- is there anything that needs to be adjusted to work with the refactored code?

### CODE REVIEW

**Comment by nathangibson** [comment]
@wsalesky Keep in mind this was and still is experimental and unpublished, so it will still be tested before going into production.

**Comment by wsalesky** [comment]
@nathangibson Hum, I forgot all about this section. I want to test the code before allowing you to merge it. Hope to get to that today, but I suspect it has some custom code in app.xql as well.

**Comment by nathangibson** [comment]
@wsalesky No problem. Actually the rest of the app wouldn't need to wait for this, right? You can just check it and merge it when ready.

**Comment by wsalesky** [comment]
Correct, as long as it is not in the app at all, if it is in the app it could cause it to fail if there are missing modules.

**Comment by nathangibson** [comment]
> Correct, as long as it is not in the app at all, if it is in the app it could cause it to fail if there are missing modules.

Ahh, I see. Would you be able to check and let me know?

**Comment by wsalesky** [comment]
It is currently not in the app, so just don't merge this pull request yet.

**Comment by wsalesky** [comment]
@nathangibson There is a lot of functionality in the texts section that does not seem to work with the current data.  Would you be okay scrapping it and starting over?

**Comment by nathangibson** [comment]
Yes. Perhaps it would help to know that what we were testing it on was /data/texts/tei/lhom-12.xml (parallel English-Arabic) and I still have to get the rest of the text data into that format. 

But I'm ok on scrapping it and restarting if you think that'll work best. If so you can close this pr.

**Comment by wsalesky** [comment]
I would rather start fresh, I will keep the code locally in case I need it, but I see a lot of issues with how it was working. Please let me know how you want the text pages to look and we can start working on those. Do you still want the multi-column display? Paging? ect.

**Comment by nathangibson** [comment]
@wsalesky OK will get back to you on this, but closing the PR.

I do still want Arabic on the right, English on the left, with paging, but we aren't using any images now.

**Pull request closed without merging**
